name: Build and Release

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Download MSP430 GCC Installer
        run: curl -L http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/9_3_1_2/export/msp430-gcc-full-linux-x64-installer-9.3.1.2.7z --output /tmp/installer.7z
      
      - name: Install Dependences
        run: sudo apt-get install -y p7zip-full cmake
      
      - name: Install MSP430 GCC Compiler
        run: |
          7z x /tmp/installer.7z -o/tmp
          sudo /tmp/msp430-gcc-full-linux-x64-installer-9.3.1.2.run --mode unattended --prefix /opt/ti/msp430-gcc

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build Project
        run: PATH=/opt/ti/msp430-gcc/bin:$PATH cmake . && cmake --build .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: ${{ github.workspace }}/smoke-detector.out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
